// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notesphere.Services.NotesphereDataAccessLayer;

#nullable disable

namespace Notesphere.Services.Migrations
{
    [DbContext(typeof(NotesphereDbContext))]
    [Migration("20251129073906_UpdatedMigration")]
    partial class UpdatedMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Notesphere.Entities.DashboardModels.QuickActions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetRoute")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QuickActions");
                });

            modelBuilder.Entity("Notesphere.Entities.DashboardModels.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReminderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("Notesphere.Entities.DashboardModels.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("Notesphere.Entities.NotesModels.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentUserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Notesphere.Entities.NotesModels.NoteExport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NoteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NoteExports");
                });

            modelBuilder.Entity("Notesphere.Entities.NotesModels.NoteTag", b =>
                {
                    b.Property<int>("NoteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NoteId", "TagId");

                    b.ToTable("NoteTags");
                });

            modelBuilder.Entity("Notesphere.Entities.NotesModels.NoteTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CssKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystemTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NoteTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CssKey = "lined",
                            DefaultContent = "",
                            Description = "Simple ruled notebook page",
                            IsSystemTemplate = true,
                            Name = "Classic lined"
                        },
                        new
                        {
                            Id = 2,
                            CssKey = "dotgrid",
                            DefaultContent = "",
                            Description = "For bullet journaling and sketches",
                            IsSystemTemplate = true,
                            Name = "Dot grid"
                        },
                        new
                        {
                            Id = 3,
                            CssKey = "cornell",
                            DefaultContent = "Topic:\nDate:\n\n[Main notes]\n\nSummary:",
                            Description = "Cue, notes, and summary layout",
                            IsSystemTemplate = true,
                            Name = "Cornell notes"
                        },
                        new
                        {
                            Id = 4,
                            CssKey = "blank",
                            DefaultContent = "",
                            Description = "Plain, no guides",
                            IsSystemTemplate = true,
                            Name = "Minimal blank"
                        });
                });

            modelBuilder.Entity("Notesphere.Entities.NotesModels.NoteVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NoteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NoteVersions");
                });

            modelBuilder.Entity("Notesphere.Entities.NotesModels.StudentUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StudentUser");
                });

            modelBuilder.Entity("Notesphere.Entities.NotesModels.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Notesphere.Entities.PlannerModels.Conflict", b =>
                {
                    b.Property<int>("ConflictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ConflictEndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConflictSeverity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConflictStartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstEventId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("OverlapDuration")
                        .HasColumnType("TEXT");

                    b.Property<int>("SecondEventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConflictId");

                    b.HasIndex("FirstEventId");

                    b.HasIndex("SecondEventId");

                    b.ToTable("Conflicts");
                });

            modelBuilder.Entity("Notesphere.Entities.PlannerModels.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecurrenceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("RecurrenceId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Notesphere.Entities.PlannerModels.RecurringEvent", b =>
                {
                    b.Property<int>("RecurrenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DaysOfWeek")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionDates")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxOccurrences")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentEventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecurrenceEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecurrenceStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("RecurrenceId");

                    b.ToTable("RecurringEvents");
                });

            modelBuilder.Entity("Notesphere.Entities.NotesModels.Note", b =>
                {
                    b.HasOne("Notesphere.Entities.NotesModels.StudentUser", "StudentUser")
                        .WithMany()
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentUser");
                });

            modelBuilder.Entity("Notesphere.Entities.PlannerModels.Conflict", b =>
                {
                    b.HasOne("Notesphere.Entities.PlannerModels.Event", "FirstEvent")
                        .WithMany()
                        .HasForeignKey("FirstEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Notesphere.Entities.PlannerModels.Event", "SecondEvent")
                        .WithMany()
                        .HasForeignKey("SecondEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstEvent");

                    b.Navigation("SecondEvent");
                });

            modelBuilder.Entity("Notesphere.Entities.PlannerModels.Event", b =>
                {
                    b.HasOne("Notesphere.Entities.PlannerModels.RecurringEvent", "RecurringEvent")
                        .WithMany("Events")
                        .HasForeignKey("RecurrenceId");

                    b.Navigation("RecurringEvent");
                });

            modelBuilder.Entity("Notesphere.Entities.PlannerModels.RecurringEvent", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
